apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .INGRESS_NAME }}"
  annotations:
    k8s.brickchain.com/dns: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/acme-dns01-provider: "clouddns"
    certmanager.k8s.io/acme-challenge-type: "dns01"
spec:
  tls:
  - hosts:
    - "{{ .URL }}"
    secretName: "tls-{{ .URL }}"
  backend:
    serviceName: realm-ng
    servicePort: 6593
  rules:
  - http:
      paths:
      - path: /realm/v2/*
        backend:
            serviceName: realm-ng
            servicePort: 6593
      - path: /realm/v2
        backend:
            serviceName: realm-ng
            servicePort: 6593
      - path: /.well-known/realm/*
        backend:
            serviceName: realm-ng
            servicePort: 6593