apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    name: redis
  name: redis
spec:
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
      name: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
          - name: storage
            mountPath: /data

  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: "redis"
  labels:
    name: redis
spec:
  selector:
    name: redis
  ports:
    - port: 6379