apiVersion: apps/v1
kind: Deployment
metadata:
  name: realm
  labels:
    app: realm
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: realm
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: realm
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets  }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /realm
          env:
            - name: LOG_LEVEL
              value: {{ .Values.log.level }}
            - name: LOG_FORMATTER
              value: {{ .Values.log.formatter}}
            - name: ADDR
              value: ":{{ .Values.port }}"
            - name: "BASE"
              value: "{{ .Values.base }}"
            - name: KEY
              value: "/secrets/key/realm.pem"
            - name: GORM_DIALECT
              value: "postgres"
            - name: "GORM_OPTIONS"
              value: "host={{ .Values.db.host }} user={{ .Values.db.user }} password={{ .Values.db.password }} dbname={{ .Values.db.name }} sslmode=disable port=5432"
          ports:
            - name: api
              containerPort: {{ .Values.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: realm-key
              mountPath: /secrets/key
      volumes:
        - name: realm-key
          secret:
            secretName: realm-key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}