{{- if .Values.realm.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    {{- toYaml .Values.realm.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: "{{ .Values.realm.ingress.hostname }}"
    http:
      paths:
      - backend:
          serviceName: realm
          servicePort: {{ .Values.realm.port }}
        path: /
  {{- if .Values.realm.ingress.tls }}
  tls:
  - hosts:
    - "{{ .Values.realm.ingress.hostname }}"
    {{- if .Values.realm.ingress.tls.secretName }}
    secretName: {{ .Values.realm.ingress.tls.secretName }}
    {{- end }}
  {{- end }}
{{- end }}