apiVersion: v1
kind: Service
metadata:
  name: realm
  labels:
    app: realm
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.realm.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.realm.service.type }}
  ports:
  - port: {{ .Values.realm.port }}
    name: api
  selector:
    app: realm